import {
  BUSINESSPROFILEPATH,
  HELPPATH,
  PROFILEMANAGEMENTPATH,
  SIGNINDELEGATEPATH,
  SIGNINPATH,
  SLASHPATH,
} from "../../constants/routes-constant";
import {
  BLOGPATH,
  BUSINESSPATH,
  CONTACTUSPATH,
  HOMEPATH,
  PERSONALPATH,
} from "../../constants/sales-site-routes-constant";

export const HEADERIMPORTS = {
  BUSINESSPROFILEPATH,
  HELPPATH,
  PROFILEMANAGEMENTPATH,
  SIGNINDELEGATEPATH,
  SIGNINPATH,
  SLASHPATH,
  BLOGPATH,
  BUSINESSPATH,
  CONTACTUSPATH,
  HOMEPATH,
  PERSONALPATH,
};
