/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        primary: "#007BFF",
        secondary: "#55AFD5",
        tertiary: "#E9F3FD",
        "primary-hover": "#0091F7",
        "primary-text": "#374151",
        "secondary-text": "#1E1F21",
        "tertiary-text": "#1F2937",
        "delegate-text": "#171721",
        "primary-background": "#FAFAFA",
        "secondary-background": "#F6F8FB",
        "alice-blue-background": "#F7F9FD",
        "tertiary-background": "#DDEDFF",
        "smoke-white": "#F3F3F3",
        "hover-background": "#EFF6FF",
        "input-background": "rgba(230, 233, 239, 0.4)",
        "white-opacity": "#ffffffc2",
        "chilly-grey": "#979797",
        grey: "#C5C7D0",
        "dull-grey": "rgba(75, 85, 99, 0.36)",
        "mild-grey": "#BFBFBF",
        "light-grey": "#E6E9EF",
        error: "#E63946",
        success: "#1AB900",
        "background-error": "#FFEEEE",
        "background-success": "#EEF9F1",
        "background-warning": "#FFEEC5",
        warning: "#EAB308",
        disabled: "#e6e9ef66",
        info: "#007Bff",
        danger: "#B51629",
        solitude: "#E9EFFD",
      },
      fontSize: {
        xs: "0.75rem",
        sm: "0.875rem",
        base: "1rem",
        lg: "1.125rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "1.875rem",
        "4xl": "2.25rem",
        "5xl": "3rem",
      },
      boxShadow: {
        sm: "0px 2px 12px rgba(0, 0, 0, 0.12)",
        md: " 0px 0px 5px 4px rgba(0, 0, 0, 0.07)",
        inner: "inset 0px 0px 3px 2px #EBEDFA",
        xl: "0px 0px 4px rgba(0, 0, 0, 0.12)",
        "2xl": "0 35px 60px -15px rgba(0, 0, 0, 0.3)",
      },
      screens: {
        sm: "576px",
        md: "768px",
        lg: "992px",
        xl: "1200px",
        "2xl": "1600px",
      },
      animation: {
        cursor: "cursor 2.6s linear infinite alternate",
        // type: 'type 1.8s ease-out .8s 1 normal both',
        type: "type 2.7s ease-out 2.8s infinite alternate both",
        "type-reverse": "type 3.8s ease-out 3s infinite alternate-reverse both",
        scale: "scale 1.7s ease-in-out infinite alternate",
      },
      keyframes: {
        type: {
          "0%": { width: "0ch" },
          "5%, 10%": { width: "1ch" },
          "15%, 20%": { width: "2ch" },
          "25%, 30%": { width: "3ch" },
          "35%, 40%": { width: "4ch" },
          "45%, 50%": { width: "5ch" },
          "55%, 60%": { width: "6ch" },
          "65%, 70%": { width: "7ch" },
        },
        scale: {
          "0%, 10%": {
            transform: "scale(1)",
            opacity: "0",
          },
          "11%, 20%": {
            transform: "scale(1.01)",
            opacity: ".1",
          },
          "21%, 30%": {
            transform: "scale(1.02)",
            opacity: ".2",
          },
          "31%, 40%": {
            transform: "scale(1.03)",
            opacity: ".3",
          },
          "41%, 50%": {
            transform: "scale(1.04)",
            opacity: ".4",
          },
          "51%, 60%": {
            transform: "scale(1.05)",
            opacity: ".5",
          },
          "61%, 70%": {
            transform: "scale(1.06)",
            opacity: ".6",
          },
          "71%, 80%": {
            transform: "scale(1.07)",
            opacity: ".7",
          },
          "81%, 90%": {
            transform: "scale(1.08)",
            opacity: ".8",
          },
          "91%, 100%": {
            transform: "scale(1.1)",
            opacity: "1",
          },
        },
      },
    },
  },
  important: true,
  plugins: [],
};
