import { ICONSCONSTANT } from "../../../constants/icons-constant";
import { disableFutureDates } from "../../../utils/date-time-utils";
import { BUSINESSDETAILSVIEWIMPORT } from "./business-details-view-import";

const provinceData = ["Zhejiang", "Jiangsu"];
export const businessDetailsFormFieldsInputFunction = () => {
  return [
    {
      heading: "Business Information",
      headingClassName: "text-base font-semibold bg-light-grey pt-3 pb-3 pl-3 mb-4",
      fields: [
        {
          id: 1,
          label: "Business Type",
          name: "businessType",
          fieldType: "select",
          size: "large",
          fieldLg: 12,
          className: "dynamic-form-select-simple",
          options: provinceData.map((x: any) => ({ value: x, label: x })),
          rules: BUSINESSDETAILSVIEWIMPORT.businessTypeFieldRules?.(),
        },
        {
          id: 2,
          label: "Legal Business Name",
          name: "legalBusinessName",
          fieldType: "input",
          size: "large",
          fieldLg: 12,
          rules: BUSINESSDETAILSVIEWIMPORT.businessNameFieldRules?.(),
        },
        {
          id: 3,
          label: "Company Registration Number",
          name: "companyRegistrationNumber",
          size: "large",
          fieldLg: 12,
          rules: BUSINESSDETAILSVIEWIMPORT.companyRegistrationNumberFieldRules?.(),
          fieldType: "input",
        },
        {
          id: 4,
          label: "Country of incorporation",
          name: "countryOfIncorporation",
          size: "large",
          fieldLg: 12,
          rules: BUSINESSDETAILSVIEWIMPORT.countryFieldRules?.(),
          fieldType: "input",
        },
        {
          id: 5,
          label: "Date of Incorporation",
          name: "doI",
          fieldType: "date",
          className: "w-full",
          size: "large",
          fieldLg: 12,
          disabledDate: (currentDate: any) => disableFutureDates(currentDate),
          rules: BUSINESSDETAILSVIEWIMPORT.dateOfIncorporationFieldRules?.(),
        },
      ],
    },
    {
      heading: "Registered Company Address",
      headingClassName: "text-base font-semibold bg-light-grey pt-3 pb-3 pl-3 mb-4",
      fields: [
        {
          id: 1,
          label: "Post Code",
          name: "postCode",
          // fieldType: "select",
          fieldType: "input",
          size: "large",
          fieldLg: 12,
          className: "dynamic-form-select-simple",
          // options: provinceData.map((x: any) => ({ value: x, label: x })),
          rules: BUSINESSDETAILSVIEWIMPORT.postCodeFieldRules?.(),
        },
        {
          id: 2,
          label: "Town/City",
          name: "city",
          fieldType: "input",
          size: "large",
          fieldLg: 12,
          rules: BUSINESSDETAILSVIEWIMPORT.cityFieldRules?.(),
        },
        {
          id: 3,
          label: "Address Line 1",
          name: "address1",
          size: "large",
          fieldLg: 12,
          rules: BUSINESSDETAILSVIEWIMPORT.addressFieldRules?.(),
          fieldType: "input",
        },
        {
          id: 4,
          label: "Address Line 2",
          name: "address2",
          size: "large",
          fieldLg: 12,
          rules: BUSINESSDETAILSVIEWIMPORT.addressFieldRules?.(),
          fieldType: "input",
        },
      ],
    },
    {
      heading: "Company Trading Address",
      headingClassName: "text-base font-semibold bg-light-grey pt-3 pb-3 pl-3 mb-4",
      fields: [
        {
          id: 1,
          label: "Post Code",
          name: "postCodeTrading",
          // fieldType: "select",
          fieldType: "input",
          size: "large",
          fieldLg: 12,
          className: "dynamic-form-select-simple",
          // options: provinceData.map((x: any) => ({ value: x, label: x })),
          rules: BUSINESSDETAILSVIEWIMPORT.postCodeFieldRules?.(),
        },
        {
          id: 2,
          label: "Town/City",
          name: "cityTrading",
          fieldType: "input",
          size: "large",
          fieldLg: 12,
          rules: BUSINESSDETAILSVIEWIMPORT.cityFieldRules?.(),
        },
        {
          id: 3,
          label: "Address Line 1",
          name: "address1Trading",
          size: "large",
          fieldLg: 12,
          rules: BUSINESSDETAILSVIEWIMPORT.addressFieldRules?.(),
          fieldType: "input",
        },
        {
          id: 4,
          label: "Address Line 2",
          name: "address2Trading",
          size: "large",
          fieldLg: 12,
          rules: BUSINESSDETAILSVIEWIMPORT.addressFieldRules?.(),
          fieldType: "input",
        },
      ],
    },
    {
      heading: "Director Information",
      headingClassName: "text-base font-semibold bg-light-grey pt-3 pb-3 pl-3 mb-4",
      fields: [
        {
          id: 1,
          label: "Name",
          name: "directorName",
          fieldType: "input",
          size: "large",
          fieldLg: 12,
          rules: BUSINESSDETAILSVIEWIMPORT.onlyNameFieldRules,
        },
        {
          id: 2,
          label: "Role",
          name: "directorRole",
          size: "large",
          fieldLg: 12,
          rules: BUSINESSDETAILSVIEWIMPORT.roleFieldRules?.(),
          fieldType: "input",
        },
        {
          id: 3,
          label: "Correspondance Address",
          name: "directorCorrespondanceAddress",
          size: "large",
          fieldLg: 12,
          rules: BUSINESSDETAILSVIEWIMPORT.addressFieldRules?.(),
          fieldType: "input",
        },
        {
          id: 5,
          label: "Date of Incorporation",
          name: "directorDoI",
          fieldType: "date",
          className: "w-full",
          size: "large",
          fieldLg: 12,
          rules: BUSINESSDETAILSVIEWIMPORT.dateOfIncorporationFieldRules?.(),
        },
      ],
    },
    {
      heading: "Business Sector",
      headingClassName: "text-base font-semibold bg-light-grey pt-3 pb-3 pl-3 mb-4",
      fields: [
        {
          id: 1,
          label: "Business Sector",
          name: "businessSector",
          fieldType: "input",
          size: "large",
          fieldLg: 12,
          rules: BUSINESSDETAILSVIEWIMPORT.businessSectorNameFieldRules?.(),
        },
        {
          id: 2,
          label: "Website (optional)",
          name: "website",
          size: "large",
          fieldLg: 12,
          // rules: [{ required: true, message: "Please enter the last name", whitespace: true }],
          fieldType: "input",
        },
        {
          id: 3,
          label: "LinkedIn (optional)",
          name: "linkedIn",
          size: "large",
          fieldLg: 12,
          // rules: [{ required: true, message: requiredFieldMessage?.("Phone Number") }],
          fieldType: "input",
        },

        {
          id: 4,
          label: "Website Logo",
          name: "logo",
          size: "large",
          // className: "w-full dynamic-form-upload-full dynamic-form-input-elegant",
          suffix: <ICONSCONSTANT.UploadOutlined />,
          fieldLg: 12,
          readOnly: true,
          // rules: [{ required: true, message: requiredFieldMessage?.("Phone Number") }],
          fieldType: "upload",
        },

        {
          id: 5,
          label: "Describe Your Business",
          name: "businessInfo",
          size: "large",
          rules: BUSINESSDETAILSVIEWIMPORT.businessInformationFieldRules?.(),
          fieldType: "input",
        },
      ],
    },
  ];
};

export const BUSINESSDETAILSVIEWDATA = {
  businessDetailsFormFieldsInputFunction,
};
