import {
  ADDBENEFICIARYPATH,
  BENEFICIARYPATH,
  BULKADDBENEFICIARYPATH,
  EDITBENEFICIARYPARAM,
  SLASHPATH,
} from "../../../constants/routes-constant";

export const BENEFICIARYLISTIMPORT = {
  ADDBENEFICIARYPATH,
  BENEFICIARYPATH,
  BULKADDBENEFICIARYPATH,
  EDITBENEFICIARYPARAM,
  SLASHPATH,
};
