import { CARDSPATH, REPORTCARDISSUEPARAM, SLASHPATH, UPSERTLIMITPARAM, ADDTOWALLETPARAM, LIMITVIEWPARAM, CHANGECARDPINPATH } from "../../../constants/routes-constant";
import { REPORTISSUEPARAMSCONSTANT, CARDTYPEPARAMSCONSTANTS, ADDTOWALLETTYPEPARAMSCONSTANTS } from "../../../constants/params-constant";

export const CARDSETTINGIMPORTS = {
    CARDSPATH,
    REPORTCARDISSUEPARAM,
    SLASHPATH,
    UPSERTLIMITPARAM,
    ADDTOWALLETPARAM,
    LIMITVIEWPARAM,
    REPORTISSUEPARAMSCONSTANT,
    CARDTYPEPARAMSCONSTANTS,
    ADDTOWALLETTYPEPARAMSCONSTANTS,
    CHANGECARDPINPATH,
}