import {
  SLASHPATH,
  TEAMROLEDETAILSPARAM,
  TEAMSMANAGEMENTPATH,
} from "../../../constants/routes-constant";

export const ADDTEAMIMPORTS = {
  SLASHPATH,
  TEAMROLEDETAILSPARAM,
  TEAMSMANAGEMENTPATH,
};
