import {
  SLASHPATH,
  SHAREDGIFTCARDLINK,
  ADDGIFTDETAILPATH,
  MOREPATH,
} from "../../../constants/routes-constant";

export const SELECTGIFTRECIPIENTIMPORTS = {
  SLASHPATH,
  SHAREDGIFTCARDLINK,
  ADDGIFTDETAILPATH,
  MOREPATH,
};
